name: Trigger Another Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a repository dispatch event
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_WORKFLOW_TOKEN }}" \
          https://api.github.com/repos/spreadsheetimporter/packed-deployment-abap/actions/workflows/updateversions.yml/dispatches \
          -d '{"ref":"main"}'
      
